version: '3'

services:
  redis:
    image: redis:7.2.0
    container_name: redis-master
    ports:
      - "${RDS_MASTER_PORT}:6379"
    networks:
      - redis-replication

  redis-replica-1:
    image: redis:7.2.0
    container_name: redis-replica-1
    ports:
      - "${RDS_REPLICA1_PORT}:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis
    networks:
      - redis-replication

  redis-replica-2:
    image: redis:7.2.0
    container_name: redis-replica-2
    ports:
      - "${RDS_REPLICA2_PORT}:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis
    networks:
      - redis-replication
networks:
  redis-replication:
    driver: bridge