version: '3'

services:
  redis:
    image: redis:7.2.0
    container_name: redis-master
    ports:
      - "${RDS_MASTER_PORT}:6379"
    networks:
      - redis-replication
    profiles:
      - 'redis'
      - 'all'
  
  redis-replica-1:
    image: redis:7.2.0
    container_name: redis-replica-1
    ports:
      - "${RDS_REPLICA1_PORT}:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis
    networks:
      - redis-replication
    profiles:
      - 'redis'
      - 'all'

  redis-replica-2:
    image: redis:7.2.0
    container_name: redis-replica-2
    ports:
      - "${RDS_REPLICA2_PORT}:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis
    networks:
      - redis-replication
    profiles:
      - 'redis'
      - 'all'
  
  redis-raft-master:
    image: redislabs/ng-redis-raft
    container_name: redis-raft-master
    command: redis-server --loadmodule /redisraft.so --raft.addr redis-raft-master:6379
    ports:
      - "6379:6379"
    networks:
      - redis-raft
    profiles:
      - 'redis-raft'
      - 'all'
    
  redis-raft-slave-1:
    image: redislabs/ng-redis-raft
    container_name: redis-raft-slave-1
    command: redis-server --loadmodule /redisraft.so --raft.addr redis-raft-slave-1:6379
    depends_on:
      - redis-raft-master
    ports:
      - "6380:6379"
    networks:
      - redis-raft
    profiles:
      - 'redis-raft'
      - 'all'

  redis-raft-slave-2:
    image: redislabs/ng-redis-raft
    container_name: redis-raft-slave-2
    command: redis-server --loadmodule /redisraft.so --raft.addr redis-raft-slave-2:6379
    depends_on:
      - redis-raft-master
    ports:
      - "6381:6379"
    networks:
      - redis-raft
    profiles:
      - 'redis-raft'
      - 'all'

  redblue-1:
    build:
      context: ./server
      dockerfile: ./Dockerfile

    container_name: redblue-1
    depends_on:
      - redblue-2
      - redblue-3
    ports:
      - "7379:7379"
    networks:
      - redblue-cluster
    profiles:
      - 'rb'
      - 'all'
    command: /redblue/redblue redblue-2 7379 redblue-3 7379

  redblue-2:
    build:
      context: ./server
      dockerfile: ./Dockerfile

    container_name: redblue-2

    ports:
      - "7380:7379"
    networks:
      - redblue-cluster
    profiles:
      - 'rb'
      - 'all'
    command: /redblue/redblue

  redblue-3:
    build:
      context: ./server
      dockerfile: ./Dockerfile

    container_name: redblue-3
    ports:
      - "7381:7379"
    networks:
      - redblue-cluster
    profiles:
      - 'rb'
      - 'all'
    command: /redblue/redblue

networks:
  redis-replication:
    driver: bridge
  redblue-cluster:
    driver: bridge
  redis-raft:
    driver: bridge